name: "PRtify CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  Prepare:
    name: Preparing
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Xcpretty
        run: gem install xcpretty --no-document --quiet
        
  Test:
    name: Run test
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-latest]
        swift: ["5.6", "5.7"]
        destination: ["platform=OS X,arch=x86_64,variant=Mac Catalyst", "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"]
        
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Setup tuist
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'fetch'
          arguments: ''

      - name: Setup Xcode
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ startsWith(matrix.swift, '5.6') }}
        with:
          xcode-version: '13.4.1'
          
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
          
      - name: Get swift version
        run: swift --version
        
      - name: Run build
        run: xcodebuild -scheme PRtify -destination '${{ matrix.destination }}' build
        
      - name: Run tests
        run: xcodebuild -scheme PRtify -destination '${{ matrix.destination }}' test -enableCodeCoverage YES
